version: "3.7"
services:
  db:
    image: mysql
    restart: "always"
    ports:
      - "1306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "GitEval"
    volumes:
      - "./db:/var/lib/mysql"
  GitEval:
    # 本地镜像
    image: "giteval:v1"
    restart: "always"
    volumes:
      - "./conf/config.yaml:/app/conf/config.yaml"
    ports:
      - "8080:8080"
    depends_on:
      - db
  llm:
    image: "llm:v1"
    restart: "always"
    ports:
      - "5000:5000"